config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"

  resources :recipes
  resources :meal_plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_plan
  belongs_to :recipe

  validates :date, presence: true
  validates :meal_plan, presence: true
  validates :recipe, presence: true
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :meals, -> { order(:date) }, inverse_of: :meal_plan, dependent: :destroy

  accepts_nested_attributes_for :meals

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true

  def build_meals
    user_recipe_ids = user.recipes.pluck(:id)

    (start_date..end_date).each do |date|
      unused_recipes = user_recipe_ids - meals.map(&:recipe_id)

      available_recipes = unused_recipes.empty? ? user_recipe_ids : unused_recipes
      meals.build(date: date, recipe_id: available_recipes.sample)
    end
  end

  def to_s
    "#{I18n.localize(start_date)} - #{I18n.localize(end_date)}"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :description, presence: true
  validates :user, presence: true

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :recipes
  has_many :meal_plans

  def recipe_options
    recipes.map do |recipe|
      [recipe.name, recipe.id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  before_action :require_login

  def new
    @meal_plan = current_user.meal_plans.build(
      start_date: params[:start_date] || Date.today,
      end_date: params[:end_date] || 6.days.from_now.to_date
    )

    @meal_plan.build_meals
  end

  def create
    @meal_plan = current_user.meal_plans.build(meal_plan_params)

    if @meal_plan.save
      redirect_to meal_plan_path(@meal_plan), notice: "Meal plan created!"
    else
      @errors = @meal_plan.errors.full_messages
      render :new
    end
  end

  def show
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def index
    @current_meal_plan = current_user.meal_plans.where("start_date <= ? AND end_date >= ?",
                         Date.today, Date.today).first
    @meal_plans = current_user.meal_plans.order("start_date desc")
  end

  def destroy
    @meal_plan = current_user.meal_plans.find(params[:id])
    @meal_plan.destroy
    redirect_to meal_plans_path, notice: "Meal plan deleted!"
  end

  def edit
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def update
    @meal_plan = current_user.meal_plans.find(params[:id])

    if @meal_plan.update_attributes(meal_plan_params)
      redirect_to meal_plan_path(@meal_plan), notice: "Meal plan updated!"
    else
      @errors = @meal_plan.errors.full_messages
      render :edit
    end
  end

  private

  def meal_plan_params
    params.require(:meal_plan).permit(
      :start_date,
      :end_date,
      meals_attributes: [
        :id,
        :date,
        :recipe_id
      ]
    )
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login

  def index
    @recipes = current_user.recipes.order(:id)
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe), notice: "Recipe Created!"
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])

    if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe), notice: "Recipe Updated!"
    else
      @errors = @recipe.errors.full_messages
      render :edit
    end
  end

  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy
    redirect_to recipes_path, notice: "Deleted Recipe: #{recipe.name}"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class(flash_type)
    case flash_type.to_sym
    when :notice
      "alert-success"
    when :alert
      "alert-warning"
    when :error
      "alert-danger"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MealPlan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "Meal Planning", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Meal Plans", meal_plans_path %></li>
              <li><%= link_to "Recipes", recipes_path %></li>
              <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", sign_in_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <section class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
        <% end %>
      </div>

      <%= yield %>
    </section>
  </body>
</html>

app/views/meal_plans/_form.html.erb
<%= render partial: "shared/errors" %>

<%= form_for @meal_plan, html: { class: "form-horizontal" } do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <div class="meal">
        <%= meal_fields.hidden_field :id %>
        <%= meal_fields.hidden_field :date %>

        <div class="form-group margin-vertical-none">
          <div class="col-sm-11 col-sm-offset-1">
            <p><%= localize(meal_fields.object.date) %></p>
          </div>
        </div>

        <div class="form-group">
          <%= meal_fields.label :recipe_id, class: "col-sm-1 control-label" %>
          <div class="col-sm-11">
            <%= meal_fields.select :recipe_id, current_user.recipe_options, {}, class: "form-control" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <div class="col-sm-11 col-sm-offset-1">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/meal_plans/edit.html.erb
<h1>Edit Meal Plan: <%= @meal_plan %></h1>

<%= render(partial: "form") %>

app/views/meal_plans/index.html.erb
<h1>Meal Plans</h1>

<% if @current_meal_plan.present? %>
  <h2>Current Meal Plan</h2>

  <div>
    <ul class="meals">
      <% @current_meal_plan.meals.each do |meal| %>
        <li class="meal">
          <%= meal.date %> - <%= link_to meal.recipe.to_s, recipe_path(meal.recipe) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>All Meal Plans</h3>

<% @meal_plans.each do |meal_plan| %>
  <div class="meal-plan">
    <%= link_to meal_plan, meal_plan_path(meal_plan) %>
  </div>
<% end %>

<div class="actions">
  <%= link_to "New Meal Plan", new_meal_plan_path %>
</div>

app/views/meal_plans/new.html.erb
<div class="title-container">
  <h1>New Meal Plan</h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for @meal_plan, url: new_meal_plan_path, method: "GET", html: { class: "form-inline" } do |form| %>
      <div class="form-group">
        <%= form.label :start_date %>
        <%= form.text_field :start_date, type: "date", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :end_date %>
        <%= form.text_field :end_date, type: "date", class: "form-control" %>
      </div>

        <%= form.submit "Generate Plan", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

<%= render(partial: "form") %>

app/views/meal_plans/show.html.erb
<h1>Meal Plan: <%= @meal_plan %></h1>

<h2>Meals</h2>

<ul class="meals">
  <% @meal_plan.meals.each do |meal| %>
    <li class="meal">
      <%= meal.date %> - <%= link_to meal.recipe, recipe_path(meal.recipe) %>
    </li>
  <% end %>
</ul>

<div class="actions">
  <ul class="recipe-actions">
    <li>
      <%= link_to "Edit Meal Plan", edit_meal_plan_path(@meal_plan) %>
    </li>
    <li><%= link_to "Delete", meal_plan_path(@meal_plan), data: {
      confirm: "Are you sure you want to delete meal plan: #{@meal_plan}?",
    }, method: :delete %></li>
  </ul>
<div>

app/views/recipes/_form.html.erb
<%= render partial: "shared/errors" %>

<%= form_for @recipe do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<div class="title-container">
  <h1>Recipes</h1>
  <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default" %>
</div>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to truncate(recipe.name), recipe_path(recipe) %></h3>
          <p><%= truncate(recipe.description, length: 150) %></p>
          <p>
            <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-default" %>
            <%= link_to "Delete", recipe_path(recipe), data: {
              confirm: "Are you sure you want to delete: #{recipe.name}?",
            }, method: :delete %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="title-container">
  <h1>New Recipe</h1>
</div>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Description:</h2>
<p><%= @recipe.description %></p>

<div>
  <ul class="recipe-actions">
    <li><%= link_to "Back", recipes_path %></li>
    <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
    <li><%= link_to "Delete", recipe_path(@recipe), data: {
      confirm: "Are you sure you want to delete: #{@recipe.name}?"
    }, method: :delete %></li>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if @errors.present? %>
  <div class="alert alert-danger errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/show.html.erb
<h1>Welcome</h1>